---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/hxnzvimy/public_html/staging2-globaltaxcompliance-com/
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R plugins $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH

    
   
 
